[workspace]
resolver = "2"
members = [
    "model",
    "resources",
    "logic",

    "construction",
    "influence",
    "connection",
    "hud",
    "collision",

    "game",
    
    "milestones/milestone-01",
    "milestones/milestone-02",
    "milestones/milestone-03",
]
