[workspace]
resolver = "2"
members = [
    "model",
    "game",
    "resources",    

    "construction",
    "influence",
    "connection",
    "hud",
    
    "milestones/milestone-01",
    "milestones/milestone-02",
    "milestones/milestone-03",
]
