[package]
name = "milestone-01"
version = "0.1.0"
edition = "2021"

[dependencies]
model = { path = "../../model" }
game = { path = "../../game" }
construction = { path = "../../construction" }
influence = { path = "../../influence" }
connection = { path = "../../connection" }

bevy = "0.7.0"
