[package]
name = "milestone-04"
version = "0.1.0"
edition = "2021"

[dependencies]
model = { path = "../../model" }
game = { path = "../../game" }

bevy = { version = "0.8.0", default-features = false, features = ["bevy_asset", "render", "bevy_winit", "png"] }
